## Bài 1. Tạo Tensor cơ bản

In [2]:
import torch

a = torch.tensor(
    [[1, 2, 3],
     [4, 5, 6]],
    dtype=torch.int32
)

print(a)

print("Kích thước:", a.shape)
print("Số chiều:", a.ndim)
print("Kiểu dữ liệu:", a.dtype)

ModuleNotFoundError: No module named 'torch'

## Bài 2. Tạo các Tensor thường dùng

In [ ]:
import torch

a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)

print("Tensor rand:")
print(a)

print("\nTensor randn:")
print(b)

print("\nTensor zeros:")
print(c)

print("\nTensor ones:")
print(d)

print("\nMa trận đơn vị:")
print(e)

# Tensor 5 x 5 toàn giá trị 10
f = torch.full((5, 5), 10)

print("\nTensor 5 x 5 toàn số 10:")
print(f)

Tensor rand:
tensor([[0.4847, 0.8355, 0.5788, 0.3116],
        [0.0856, 0.8393, 0.4565, 0.0778],
        [0.9192, 0.0819, 0.4574, 0.3393]])

Tensor randn:
tensor([[-1.6392, -0.3909,  0.2518, -0.0354],
        [-0.7761,  0.5800, -0.3224,  1.1811],
        [ 0.3657, -0.9986, -0.3246, -1.5985]])

Tensor zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Tensor ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Ma trận đơn vị:
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

Tensor 5 x 5 toàn số 10:
tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


## Bài 3. Kiểm tra thông tin Tensor

In [ ]:
import torch

a = torch.zeros(2, 3, 4)

print("Tensor:")
print(a)

print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


## Bài 4. Slicing và Indexing

In [ ]:
import torch

a = torch.randn(3, 4, 5)

print("Original tensor:")
print(a)

print("\nTensor a[1]:")
print(a[1])

print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

# Lấy hai phần tử cuối cùng trên chiều thứ ba
print("\nHai phần tử cuối trên chiều thứ ba:")
print(a[:, :, -2:])

Original tensor:
tensor([[[ 0.7193,  2.7598,  0.4217,  1.2166,  0.7531],
         [ 2.1774, -0.4606, -0.7627, -0.3185, -1.6679],
         [-1.4454, -0.6177,  1.0853, -0.1744,  1.2652],
         [-0.9344, -1.0119, -0.8237,  0.2845,  0.2499]],

        [[ 0.6388,  0.4844, -0.3535, -1.8872,  1.1635],
         [-0.2703, -1.5011,  0.4924,  0.2820,  0.0393],
         [ 0.7154, -0.6994, -0.4255,  1.4126,  0.5781],
         [-2.2769,  0.0646, -0.1136, -1.6729,  0.7694]],

        [[-0.7180, -0.5238, -0.4309,  0.8219, -0.9199],
         [-0.7785,  0.6802, -0.0794, -1.5880,  0.5157],
         [-1.5109, -0.4709, -0.6802, -1.3962, -0.9868],
         [ 1.4286,  2.2903,  0.9991, -1.1599,  0.4842]]])

Tensor a[1]:
tensor([[ 0.6388,  0.4844, -0.3535, -1.8872,  1.1635],
        [-0.2703, -1.5011,  0.4924,  0.2820,  0.0393],
        [ 0.7154, -0.6994, -0.4255,  1.4126,  0.5781],
        [-2.2769,  0.0646, -0.1136, -1.6729,  0.7694]])

Tensor a[1:, 2:4]:
tensor([[[ 0.7154, -0.6994, -0.4255,  1.4126,  0.5

## Bài 5. Reshape và Flatten

In [ ]:
import torch

a = torch.randn(3, 4)

print("Original:")
print(a)

print("\nFlatten:")
print(a.ravel())

print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

# Kiểm tra số phần tử
print("\nSố phần tử ban đầu:", a.numel())
print("Số phần tử sau reshape:", a.reshape(3, 2, 2).numel())

# Reshape thành 2 x 6
print("\nReshape to 2 x 6:")
print(a.reshape(2, 6))

Original:
tensor([[-1.3893,  0.7535,  0.8406,  2.0019],
        [ 0.0073, -1.8613, -0.3864, -1.3650],
        [-1.2293,  1.6275, -0.6657,  0.6997]])

Flatten:
tensor([-1.3893,  0.7535,  0.8406,  2.0019,  0.0073, -1.8613, -0.3864, -1.3650,
        -1.2293,  1.6275, -0.6657,  0.6997])

Reshape to 3 x 2 x 2:
tensor([[[-1.3893,  0.7535],
         [ 0.8406,  2.0019]],

        [[ 0.0073, -1.8613],
         [-0.3864, -1.3650]],

        [[-1.2293,  1.6275],
         [-0.6657,  0.6997]]])

Số phần tử ban đầu: 12
Số phần tử sau reshape: 12

Reshape to 2 x 6:
tensor([[-1.3893,  0.7535,  0.8406,  2.0019,  0.0073, -1.8613],
        [-0.3864, -1.3650, -1.2293,  1.6275, -0.6657,  0.6997]])


## Bài 6. Phép toán và nhân ma trận

In [ ]:
import torch

a = torch.randn(2, 3)
b = torch.randn(2, 3)

print("a:")
print(a)

print("b:")
print(b)

print("\na + b:")
print(a + b)

print("\na / b:")
print(a / b)

print("\na^2:")
print(a ** 2)

print("\na * b:")
print(a * b)

print("\nMatrix multiplication:")
print(a @ b.T)

print("\nShape của a @ b.T:")
print((a @ b.T).shape)

a:
tensor([[-0.1647, -0.5001, -0.7997],
        [-0.6589,  1.9289,  0.4032]])
b:
tensor([[-1.0489, -1.3043, -0.1839],
        [-1.9161,  0.4283,  0.0239]])

a + b:
tensor([[-1.2135, -1.8044, -0.9836],
        [-2.5750,  2.3572,  0.4271]])

a / b:
tensor([[ 0.1570,  0.3834,  4.3485],
        [ 0.3439,  4.5041, 16.8931]])

a^2:
tensor([[0.0271, 0.2501, 0.6395],
        [0.4341, 3.7208, 0.1626]])

a * b:
tensor([[0.1727, 0.6523, 0.1471],
        [1.2625, 0.8261, 0.0096]])

Matrix multiplication:
tensor([[ 0.9720,  0.0822],
        [-1.8988,  2.0982]])

Shape của a @ b.T:
torch.Size([2, 2])


## Bài 7. Các hàm thống kê trên Tensor

In [ ]:
import torch

a = torch.randn(3, 4)

print("Tensor a:")
print(a)

print("\nMean theo cột:")
print(torch.mean(a, dim=0))

print("\nStandard deviation theo cột:")
print(torch.std(a, dim=0))

print("\nCumulative sum theo cột:")
print(torch.cumsum(a, dim=0))

# Thử với dim=1
print("\nMean với dim=1:")
print(torch.mean(a, dim=1))

print("\nStandard deviation với dim=1:")
print(torch.std(a, dim=1))

print("\nCumulative sum với dim=1:")
print(torch.cumsum(a, dim=1))

Tensor a:
tensor([[ 0.9412, -0.0092,  0.3120, -1.6748],
        [-0.3725,  0.4905,  1.1018, -1.6687],
        [ 0.4135,  0.3087,  0.1594, -0.4206]])

Mean theo cột:
tensor([ 0.3274,  0.2633,  0.5244, -1.2547])

Standard deviation theo cột:
tensor([0.6610, 0.2529, 0.5059, 0.7223])

Cumulative sum theo cột:
tensor([[ 0.9412, -0.0092,  0.3120, -1.6748],
        [ 0.5687,  0.4813,  1.4138, -3.3435],
        [ 0.9822,  0.7899,  1.5731, -3.7642]])

Mean với dim=1:
tensor([-0.1077, -0.1122,  0.1152])

Standard deviation với dim=1:
tensor([1.1168, 1.2010, 0.3721])

Cumulative sum với dim=1:
tensor([[ 0.9412,  0.9319,  1.2439, -0.4309],
        [-0.3725,  0.1180,  1.2198, -0.4489],
        [ 0.4135,  0.7221,  0.8815,  0.4608]])


## Bài 8. Autograd cơ bản

In [ ]:
import torch

x = torch.tensor(
    3.6,
    requires_grad=True
)

y = x * x

y.backward()

print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


## Bài 9. Gradient Descent tìm hệ số đa thức

In [ ]:
import numpy as np
import torch

# Tạo đa thức y = x^2 + 2x + 3
polynomial = np.poly1d([1, 2, 3])

# Tạo 20 dữ liệu ngẫu nhiên
N = 20
X = np.random.randn(N, 1) * 5

# Tính Y theo đa thức
Y = polynomial(X)

# Tạo ma trận dữ liệu [x^2, x, 1]
XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

# Tạo 3 hệ số ngẫu nhiên cần tìm
w = torch.randn(3, 1, requires_grad=True)

# Chuyển dữ liệu NumPy sang Tensor
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

# Tạo optimizer NAdam
optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)

# Huấn luyện
for epoch in range(1000):
    optimizer.zero_grad()

    y_pred = x @ w

    mse = torch.mean(torch.square(y - y_pred))

    mse.backward()

    optimizer.step()

print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[-1.6267],
        [-0.3686],
        [ 0.3270]], requires_grad=True)
Learned coefficients:
tensor([[0.9924],
        [2.1019],
        [2.9942]], requires_grad=True)


## Bài 10. Giải hệ phương trình bằng Autograd

In [ ]:
import random
import torch

A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)

EPOCHS = 2000

optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)

for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2

    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4

    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()

print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

# Kiểm tra 4 phương trình
print("\nKiểm tra:")
print("A + B =", A + B)
print("C - D =", C - D)
print("A + C =", A + C)
print("B - D =", B - D)

A = tensor(4.6738, requires_grad=True)
B = tensor(4.3261, requires_grad=True)
C = tensor(3.3261, requires_grad=True)
D = tensor(2.3261, requires_grad=True)

Kiểm tra:
A + B = tensor(8.9999, grad_fn=<AddBackward0>)
C - D = tensor(1.0000, grad_fn=<SubBackward0>)
A + C = tensor(8.0000, grad_fn=<AddBackward0>)
B - D = tensor(2.0000, grad_fn=<SubBackward0>)


## Bài 11. Các bài tập tổng hợp

In [ ]:
import torch
import numpy as np



X = torch.arange(24)

print("Tensor X ban đầu:")
print(X)

print("\nX reshape thành 4 x 6:")
print(X.reshape(4, 6))

print("\nX reshape thành 2 x 12:")
print(X.reshape(2, 12))

print("\nX reshape thành 2 x 3 x 4:")
print(X.reshape(2, 3, 4))




A = torch.randn(3, 4)
B = torch.randn(3, 4)

print("\n\nTensor A:")
print(A)

print("\nTensor B:")
print(B)

print("\nA + B:")
print(A + B)

print("\nA * B:")
print(A * B)

print("\nA / B:")
print(A / B)

print("\nTrung bình theo cột của A:")
print(torch.mean(A, dim=0))

print("\nĐộ lệch chuẩn theo cột của A:")
print(torch.std(A, dim=0))




x = torch.tensor(2.0, requires_grad=True)

y = 2 * x**2 + 5 * x + 3

y.backward()

print("\n\nAutograd:")
print("x =", x)
print("y =", y)
print("dy/dx =", x.grad)



print("Tính thủ công: dy/dx = 4*2 + 5 =", 13)




polynomial = np.poly1d([2, -3, 5])

N = 20

X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True)

x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

for epoch in range(1000):
    optimizer.zero_grad()

    y_pred = x @ w

    mse = torch.mean(torch.square(y - y_pred))

    mse.backward()

    optimizer.step()

print("\n\nHệ số thực tế:")
print("[2, -3, 5]")

print("\nCác hệ số tìm được:")
print(w.detach())

Tensor X ban đầu:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

X reshape thành 4 x 6:
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

X reshape thành 2 x 12:
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

X reshape thành 2 x 3 x 4:
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


Tensor A:
tensor([[ 1.4474,  0.3423,  2.0783,  0.2516],
        [ 0.5753, -1.4976,  0.0778,  0.9372],
        [ 0.0930,  0.5319,  0.4816,  0.9216]])

Tensor B:
tensor([[ 1.7680, -0.5163, -0.5521,  1.7092],
        [-0.7516,  0.0864,  1.2074,  0.3062],
        [-0.0342,  1.7024, -0.5817, -1.0579]])

A + B:
tensor([[ 3.2154, -0.1740,  1.5263,  1.9608],
        [-0.1763,